# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\emils\OneDrive\Skrivbord\Python\reinforcement_learning\reinforcement_learning\ui\firstUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QOpenGLWidget
from PyQt5.QtGui import QOpenGLBuffer, QOpenGLVertexArrayObject, QOpenGLShaderProgram
from PyQt5.QtCore import Qt
from OpenGL.GL import *
import sys
import numpy as np  
import qlwidget

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.openGLWidget = qlwidget.OpenGLWidget(self.centralwidget)
        self.openGLWidget.setGeometry(QtCore.QRect(190, 100, 571, 421))
        self.openGLWidget.setObjectName("openGLWidget")
        
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(10, 10, 121, 23))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(10, 40, 101, 23))
        self.checkBox_2.setObjectName("checkBox_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 31))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_object = QtWidgets.QAction(MainWindow)
        self.actionLoad_object.setObjectName("actionLoad_object")
        self.actionnogot = QtWidgets.QAction(MainWindow)
        self.actionnogot.setObjectName("actionnogot")
        self.action222 = QtWidgets.QAction(MainWindow)
        self.action222.setObjectName("action222")
        self.menuFile.addAction(self.actionLoad_object)
        self.menuFile.addAction(self.actionnogot)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action222)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.checkBox.setText(_translate("MainWindow", "Show body"))
        self.checkBox_2.setText(_translate("MainWindow", "box2"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionLoad_object.setText(_translate("MainWindow", "Load object"))
        self.actionnogot.setText(_translate("MainWindow", "nogot"))
        self.action222.setText(_translate("MainWindow", "222"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
